import { Station } from "./station";

export const STATIONS: Station[] = [
    {line: 'green yellow', name: 'Greenbelt', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'College Park-U of Md', transfer: false, transferLines: ''},
    {line: 'green yellow', name: "Prince George's Plaza", transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'West Hyayysville', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'Fort Totten', transfer: false, transferLines: 'yellow green red'},
    {line: 'green yellow', name: 'Georgia Ave-Petworth', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'Columbia Heights', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'U St', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'Shaw-Howard U', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'Mt Vernon Sq', transfer: false, transferLines: ''},
    {line: 'green yellow', name: 'Gallery Place', transfer: false, transferLines: 'yellow green red'},
    {line: 'green yellow', name: 'Archives', transfer: false, transferLines: ''},
    {line: 'green yellow', name: "L'Enfant Plaza", transfer: false, transferLines: 'yellow green orange silver blue'},
    {line: 'green', name: 'Waterfront', transfer: false, transferLines: ''},
    {line: 'green', name: 'Navy Yard-Ballpark', transfer: false, transferLines: ''},
    {line: 'green', name: 'Anacostia', transfer: false, transferLines: ''},
    {line: 'green', name: 'Congress Heights', transfer: false, transferLines: ''},
    {line: 'green', name: 'Southern Ave', transfer: false, transferLines: ''},
    {line: 'green', name: 'Naylor Rd', transfer: false, transferLines: ''},
    {line: 'green', name: 'Suitland', transfer: false, transferLines: ''},
    {line: 'green', name: 'Branch Ave', transfer: false, transferLines: ''},
    {line: 'red', name: 'Glenmont', transfer: false, transferLines: ''},
    {line: 'red', name: 'Wheaton', transfer: false, transferLines: ''},
    {line: 'red', name: 'Forest Glen', transfer: false, transferLines: ''},
    {line: 'red', name: 'Silver Spring', transfer: false, transferLines: ''},
    {line: 'red', name: 'Takoma', transfer: false, transferLines: ''},
    {line: 'red', name: 'Fort Totten', transfer: false, transferLines: 'red green yellow'},
    {line: 'red', name: 'Brookland-CUA', transfer: false, transferLines: ''},
    {line: 'red', name: 'Rhode Island Ave', transfer: false, transferLines: ''},
    {line: 'red', name: 'NoMa-Gallaudet U', transfer: false, transferLines: ''},
    {line: 'red', name: 'Union Station', transfer: false, transferLines: ''},
    {line: 'red', name: 'Judiciary Square', transfer: false, transferLines: ''},
    {line: 'red', name: 'Gallery Place', transfer: false, transferLines: 'red green yellow'},
    {line: 'red', name: 'Metro Center', transfer: false, transferLines: 'orange silver blue red'},
    {line: 'red', name: 'Farragut North', transfer: false, transferLines: ''},
    {line: 'red', name: 'Dupont Circle', transfer: false, transferLines: ''},
    {line: 'red', name: 'Woodley Park', transfer: false, transferLines: ''},
    {line: 'red', name: 'Cleveland Park', transfer: false, transferLines: ''},
    {line: 'red', name: 'Van Ness-UDC', transfer: false, transferLines: ''},
    {line: 'red', name: 'Tenleytown-AU', transfer: false, transferLines: ''},
    {line: 'red', name: 'Friendship Heights', transfer: false, transferLines: ''},
    {line: 'red', name: 'Bethesda', transfer: false, transferLines: ''},
    {line: 'red', name: 'Medical Center', transfer: false, transferLines: ''},
    {line: 'red', name: 'Grosvenor-Strathmore', transfer: false, transferLines: ''},
    {line: 'red', name: 'White Flint', transfer: false, transferLines: ''},
    {line: 'red', name: 'Twinbrook', transfer: false, transferLines: ''},
    {line: 'red', name: 'Rockville', transfer: false, transferLines: ''},
    {line: 'red', name: 'Shady Grove', transfer: false, transferLines: ''},
    {line: 'orange', name: 'New Carrollton', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Landover', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Cheverly', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Deanwood', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Minnesota Ave', transfer: false, transferLines: ''},
    {line: 'blue silver', name: 'Largo Town Center', transfer: false, transferLines: ''},
    {line: 'blue silver', name: 'Morgan Blvd', transfer: false, transferLines: ''},
    {line: 'blue silver', name: 'Addison Rd', transfer: false, transferLines: ''},
    {line: 'blue silver', name: 'Capitol Heights', transfer: false, transferLines: ''},
    {line: 'blue silver', name: 'Benning Rd', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Stadium-Armory', transfer: false, transferLines: 'orange silver blue'},
    {line: 'blue silver orange', name: 'Potomac Ave', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Eastern Market', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Capitol South', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Federal Center SW', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: "L'Enfant Plaza", transfer: false, transferLines: 'orange silver blue yellow green'},
    {line: 'blue silver orange', name: 'Smithsonian', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Federal Triangle', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Metro Center', transfer: false, transferLines: 'orange silver blue red'},
    {line: 'blue silver orange', name: 'McPherson Sq', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Farragut West', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Foggy Bottom-GWU', transfer: false, transferLines: ''},
    {line: 'blue silver orange', name: 'Rosslyn', transfer: false, transferLines: 'orange silver blue'},
    {line: 'blue', name: 'Arlington Cemetery', transfer: false, transferLines: ''},
    {line: 'blue yellow', name: 'Pentagon', transfer: false, transferLines: 'blue yellow'},
    {line: 'blue yellow', name: 'Pentagon City', transfer: false, transferLines: ''},
    {line: 'blue yellow', name: 'Crystal City', transfer: false, transferLines: ''},
    {line: 'blue yellow', name: 'Washington National Airport', transfer: false, transferLines: ''},
    {line: 'blue yellow', name: 'Braddock Rd', transfer: false, transferLines: ''},
    {line: 'blue yellow', name: 'King St-Old Town', transfer: false, transferLines: 'blue yellow'},
    {line: 'yellow', name: 'Eisenhower Ave', transfer: false, transferLines: ''},
    {line: 'yellow', name: 'Huntington', transfer: false, transferLines: ''},
    {line: 'blue', name: 'Van Dorn St', transfer: false, transferLines: ''},
    {line: 'blue', name: 'Franconia-Springfield', transfer: false, transferLines: ''},
    {line: 'silver orange', name: 'Court House', transfer: false, transferLines: ''},
    {line: 'silver orange', name: 'Clarendon', transfer: false, transferLines: ''},
    {line: 'silver orange', name: 'Virginia Sq-GMU', transfer: false, transferLines: ''},
    {line: 'silver orange', name: 'Ballston-MU', transfer: false, transferLines: ''},
    {line: 'silver orange', name: 'East Falls Church', transfer: false, transferLines: 'orange silver'},
    {line: 'silver', name: 'McLean', transfer: false, transferLines: ''},
    {line: 'silver', name: 'Tysons Corner', transfer: false, transferLines: ''},
    {line: 'silver', name: 'Greensboro', transfer: false, transferLines: ''},
    {line: 'silver', name: 'Spring Hill', transfer: false, transferLines: ''},
    {line: 'silver', name: 'Wiehle-Reston East', transfer: false, transferLines: ''},
    {line: 'orange', name: 'West Falls Church', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Dunn Loring', transfer: false, transferLines: ''},
    {line: 'orange', name: 'Vienna', transfer: false, transferLines: ''},
];