import { Station } from "./station";

export const STATIONS: Station[] = [
    {line: 'green yellow', name: 'Greenbelt'},
    {line: 'green yellow', name: 'College Park-U of Md'},
    {line: 'green yellow', name: "Prince George's Plaza"},
    {line: 'green yellow', name: 'West Hyayysville'},
    {line: 'green yellow', name: 'Fort Totten'},
    {line: 'green yellow', name: 'Georgia Ave-Petworth'},
    {line: 'green yellow', name: 'Columbia Heights'},
    {line: 'green yellow', name: 'U St'},
    {line: 'green yellow', name: 'Shaw-Howard U'},
    {line: 'green yellow', name: 'Mt Vernon Sq'},
    {line: 'green yellow', name: 'Gallery Place'},
    {line: 'green yellow', name: 'Archives'},
    {line: 'green yellow', name: "L'Enfant Plaza"},
    {line: 'green', name: 'Waterfront'},
    {line: 'green', name: 'Navy Yard-Ballpark'},
    {line: 'green', name: 'Anacostia'},
    {line: 'green', name: 'Congress Heights'},
    {line: 'green', name: 'Southern Ave'},
    {line: 'green', name: 'Naylor Rd'},
    {line: 'green', name: 'Suitland'},
    {line: 'green', name: 'Branch Ave'},
    {line: 'red', name: 'Glenmont'},
    {line: 'red', name: 'Wheaton'},
    {line: 'red', name: 'Forest Glen'},
    {line: 'red', name: 'Silver Spring'},
    {line: 'red', name: 'Takoma'},
    {line: 'red', name: 'Brookland-CUA'},
    {line: 'red', name: 'Rhode Island Ave'},
    {line: 'red', name: 'NoMa-Gallaudet U'},
    {line: 'red', name: 'Union Station'},
    {line: 'red', name: 'Judiciary Square'},
    {line: 'red', name: 'Gallery Place'},
    {line: 'red', name: 'Metro Center'},
    {line: 'red', name: 'Farragut North'},
    {line: 'red', name: 'Dupont Circle'},
    {line: 'red', name: 'Woodley Park'},
    {line: 'red', name: 'Cleveland Park'},
    {line: 'red', name: 'Van Ness-UDC'},
    {line: 'red', name: 'Tenleytown-AU'},
    {line: 'red', name: 'Friendship Heights'},
    {line: 'red', name: 'Bethesda'},
    {line: 'red', name: 'Medical Center'},
    {line: 'red', name: 'Grosvenor-Strathmore'},
    {line: 'red', name: 'White Flint'},
    {line: 'red', name: 'Twinbrook'},
    {line: 'red', name: 'Rockville'},
    {line: 'red', name: 'Shady Grove'},
    {line: 'orange', name: 'New Carrollton'},
    {line: 'orange', name: 'Landover'},
    {line: 'orange', name: 'Cheverly'},
    {line: 'orange', name: 'Deanwood'},
    {line: 'orange', name: 'Minnesota Ave'},
    {line: 'blue silver', name: 'Largo Town Center'},
    {line: 'blue silver', name: 'Morgan Blvd'},
    {line: 'blue silver', name: 'Addison Rd'},
    {line: 'blue silver', name: 'Capitol Heights'},
    {line: 'blue silver', name: 'Benning Rd'},
    {line: 'blue silver orange', name: 'Stadium-Armory'},
    {line: 'blue silver orange', name: 'Potomac Ave'},
    {line: 'blue silver orange', name: 'Eastern Market'},
    {line: 'blue silver orange', name: 'Capitol South'},
    {line: 'blue silver orange', name: 'Federal Center SW'},
    {line: 'blue silver orange', name: "L'Enfant Plaza"},
    {line: 'blue silver orange', name: 'Smithsonian'},
    {line: 'blue silver orange', name: 'Federal Triangle'},
    {line: 'blue silver orange', name: 'Metro Center'},
    {line: 'blue silver orange', name: 'McPherson Sq'},
    {line: 'blue silver orange', name: 'Farragut West'},
    {line: 'blue silver orange', name: 'Foggy Bottom-GWU'},
    {line: 'blue silver orange', name: 'Rosslyn'},
    {line: 'blue', name: 'Arlington Cemetery'},
    {line: 'blue yellow', name: 'Pentagon'},
    {line: 'blue yellow', name: 'Pentagon City'},
    {line: 'blue yellow', name: 'Crystal City'},
    {line: 'blue yellow', name: 'Washington National Airport'},
    {line: 'blue yellow', name: 'Braddock Rd'},
    {line: 'blue yellow', name: 'King St-Old Town'},
    {line: 'yellow', name: 'Eisenhower Ave'},
    {line: 'yellow', name: 'Huntington'},
    {line: 'blue', name: 'Van Dorn St'},
    {line: 'blue', name: 'Franconia-Springfield'},
    {line: 'silver orange', name: 'Court House'},
    {line: 'silver orange', name: 'Clarendon'},
    {line: 'silver orange', name: 'Virginia Sq-GMU'},
    {line: 'silver orange', name: 'Ballston-MU'},
    {line: 'silver orange', name: 'East Falls Church'},
    {line: 'silver', name: 'McLean'},
    {line: 'silver', name: 'Tysons Corner'},
    {line: 'silver', name: 'Greensboro'},
    {line: 'silver', name: 'Spring Hill'},
    {line: 'silver', name: 'Wiehle-Reston East'},
    {line: 'orange', name: 'West Falls Church'},
    {line: 'orange', name: 'Dunn Loring'},
    {line: 'orange', name: 'Vienna'},


];